### ISSUE TITLE
I don't know why it wont work

### ISSUE THREAD

**Issue by Erik-Da-coder** [CubeGPT/BukkitGPT#15]
[1/3] Generating codes with model gpt-4-turbo-preview...
This step may take 1 to 2 minutes, depending on the complexity of the project.
Traceback (most recent call last):
  File "/workspaces/BukkitGPT/console.py", line 63, in <module>
    build_result = core.generate_plugin(working_path, description, package_id, artifact_name, package_list)
  File "/workspaces/BukkitGPT/core.py", line 113, in generate_plugin
    code_reponse = askgpt(SYS_GEN, USR_GEN, CODING_MODEL)
  File "/workspaces/BukkitGPT/core.py", line 39, in askgpt
    response = client.chat.completions.create(
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1233, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/_base_client.py", line 922, in request
    return self._request(
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1013, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: yourapikey. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by Erik-Da-coder** [comment]
Nvm I fxed it turns out you meant config.yaml not config.py

**Comment by Erik-Da-coder** [comment]
But now i get this 
[1/3] Generating codes with model gpt-4-turbo-preview...
This step may take 1 to 2 minutes, depending on the complexity of the project.
Traceback (most recent call last):
  File "/workspaces/BukkitGPT/console.py", line 63, in <module>
    build_result = core.generate_plugin(working_path, description, package_id, artifact_name, package_list)
  File "/workspaces/BukkitGPT/core.py", line 113, in generate_plugin
    code_reponse = askgpt(SYS_GEN, USR_GEN, CODING_MODEL)
  File "/workspaces/BukkitGPT/core.py", line 39, in askgpt
    response = client.chat.completions.create(
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1233, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/_base_client.py", line 922, in request
    return self._request(
  File "/home/codespace/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1013, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by Zhou-Shilin** [comment]
Well, this is because you don't have the access to the model `gpt-4-turbo-preview`. If you're using the official api from OpenAI, you need to request one.

**Comment by Zhou-Shilin** [comment]
> GPT-4 is available in the OpenAI API to [paying customers](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4).
> —— OpenAI Documentation

*You have to pay at least 1 dollar to OpenAI for unlocking model `gpt-4-turbo-preview` and other gpt-4s.

**Comment by Erik-Da-coder** [comment]
Ok thanks a lot!

**Comment by Zhou-Shilin** [comment]
> Ok thanks a lot!

You can try some unofficial api sources if you don't want to pay like [this](https://github.com/chatanywhere/GPT_API_free). It seems like they provide a free key that can use gpt-4s model 3 times a day.

**Comment by Zhou-Shilin** [comment]
I can provide you a free apikey with the access of gpt 4 if you don't have much money. add me on discord: #baimoqilin
But you need to make sure you don't abuse it, and don't forget to tell your friends about BukkitGPT and the subsequent BuilderGPT project that  can generate Minecraft structures~!

**Comment by Erik-Da-coder** [comment]
Ok I will later today. I won't abuse it. And I will tell all my friends about your projects
.
